version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 50
  method-count:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 10
  file-lines:
    enabled: true
    config:
      threshold: 350
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "lib/"
- "example/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/\.*.js"
- "**/webpack.config.js"

